const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const outputFile = path.join(rootDir, 'src', 'environments', 'sentry-release.ts');
const buildDir = path.join(rootDir, 'www');
const defaultOrg = 'bawes-co';
const defaultProject = 'sh-staff-app';

function env(name, fallback = '') {
  return (process.env[name] || fallback).trim();
}

function project() {
  return env('SENTRY_PROJECT', defaultProject);
}

function org() {
  return env('SENTRY_ORG', defaultOrg);
}

function release() {
  const value = env('SENTRY_RELEASE') || env('COMMIT_REF');

  if (!value) {
    return '';
  }

  const prefix = `${project()}@`;
  return value.startsWith(prefix) ? value : `${prefix}${value}`;
}

function writeReleaseFile(value) {
  const contents = `// Generated by scripts/sentry-build.js during the build.\nexport const sentryRelease = ${JSON.stringify(value)};\n`;
  fs.writeFileSync(outputFile, contents);
  console.log(value ? `Wrote Sentry release ${value}` : 'Wrote empty Sentry release');
}

function sentryCliPath() {
  const executable = process.platform === 'win32' ? 'sentry-cli.cmd' : 'sentry-cli';
  const localPath = path.join(rootDir, 'node_modules', '.bin', executable);

  if (!fs.existsSync(localPath)) {
    throw new Error('sentry-cli is missing. Run npm install before building.');
  }

  return localPath;
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    env: {
      ...process.env,
      SENTRY_ORG: org(),
      SENTRY_PROJECT: project(),
    },
    stdio: options.capture ? 'pipe' : 'inherit',
    encoding: 'utf8',
  });

  if (result.error) {
    throw result.error;
  }

  return result;
}

function runSentry(args, options) {
  return run(sentryCliPath(), args, options);
}

function createRelease(value) {
  const result = runSentry(['releases', 'new', value], { capture: true });

  if (result.status === 0) {
    process.stdout.write(result.stdout || '');
    process.stderr.write(result.stderr || '');
    return;
  }

  const output = `${result.stdout || ''}${result.stderr || ''}`;
  if (/already exists/i.test(output)) {
    console.log(`Sentry release ${value} already exists`);
    return;
  }

  process.stdout.write(result.stdout || '');
  process.stderr.write(result.stderr || '');
  throw new Error(`Failed to create Sentry release ${value}`);
}

function runRequiredSentry(args, label) {
  const result = runSentry(args);

  if (result.status !== 0) {
    throw new Error(`${label} failed`);
  }
}

function runOptionalSentry(args, label) {
  const result = runSentry(args);

  if (result.status !== 0) {
    console.warn(`${label} failed; continuing.`);
  }
}

function createDeploy(value) {
  const result = runSentry(['releases', 'deploys', value, 'new', '-e', 'production'], { capture: true });

  if (result.status === 0) {
    process.stdout.write(result.stdout || '');
    process.stderr.write(result.stderr || '');
    return;
  }

  process.stdout.write(result.stdout || '');
  process.stderr.write(result.stderr || '');
  console.warn(`Could not create Sentry deploy record for ${value}; continuing after source map upload.`);
}

function deleteMaps(dir) {
  if (!fs.existsSync(dir)) {
    return;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  entries.forEach((entry) => {
    const currentPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      deleteMaps(currentPath);
      return;
    }

    if (!entry.isFile() || !entry.name.endsWith('.map')) {
      return;
    }

    try {
      fs.unlinkSync(currentPath);
      console.log(`Deleted source map ${path.relative(rootDir, currentPath)}`);
    } catch (error) {
      console.warn(`Could not delete source map ${path.relative(rootDir, currentPath)}: ${error.message}`);
    }
  });
}

function prebuild() {
  writeReleaseFile(release());
}

function postbuild() {
  const value = release();

  try {
    if (!value) {
      console.log('Skipping Sentry source map upload because no release was provided.');
      return;
    }

    if (!env('SENTRY_AUTH_TOKEN')) {
      console.log('Skipping Sentry source map upload because SENTRY_AUTH_TOKEN is not set.');
      return;
    }

    createRelease(value);
    runOptionalSentry(['releases', 'set-commits', value, '--auto'], 'Setting Sentry release commits');
    runRequiredSentry(['sourcemaps', 'inject', './www'], 'Injecting Sentry source maps');
    runRequiredSentry(['sourcemaps', 'upload', './www', '--release', value], 'Uploading Sentry source maps');
    runRequiredSentry(['releases', 'finalize', value], 'Finalizing Sentry release');
    createDeploy(value);
  } finally {
    deleteMaps(buildDir);
  }
}

const command = process.argv[2];

if (command === 'prebuild') {
  prebuild();
} else if (command === 'postbuild') {
  postbuild();
} else {
  console.error('Usage: node scripts/sentry-build.js <prebuild|postbuild>');
  process.exit(1);
}
